name: Android CI

env:
  main_project_module: app
  GRADLE_VERSION: 7.3.3

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set current date as env variable
      run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Set repository name as env variable
      run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Verify with Gradle
      run: ./gradlew check


    - name: Build apk release project (APK) - ${{ env.main_project_module }} module
      run: ./gradlew ${{ env.main_project_module }}:assembleRelease


    - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
      run: ./gradlew ${{ env.main_project_module }}:bundleRelease




      
